### ISSUE TITLE
A Question regarding the loss

### ISSUE THREAD

**Issue by wchen99998** [lanl/LFIS#1]
https://github.com/lanl/LFIS/blob/ee8b4d5ce72937494d7bb0913305f99382fed862/src/LFIS/LF/LF.py#L61

Am I mistaken or this should not be a minus? Thanks

**Comment by wchen99998** [comment]
Nvm, it appears your RHS is actually negative dt_log_p_tilder

**Comment by dblueeye** [comment]
Yes, there was a last-minute flip of sign when we wrote the manuscript. Thank you for your interest and sorry for the confusion!


—-—— —

Yen Ting Lin, PhD

Staff Scientist

CCS-3 Information Sciences Group

Computer, Computational and Statistical Sciences Division

+1 505-606-8038

TA-03, 508, 105

Los Alamos National Laboratory

________________________________
From: Chen Wuhao ***@***.***>
Sent: Monday, October 7, 2024 5:33:24 AM
To: lanl/LFIS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [lanl/LFIS] A Question regarding the loss (Issue #1)


Nvm, it appears your RHS is actually negative dt_log_p_tilder

**Comment by wchen99998** [comment]
Thanks for the reply. I'll close this one then. Have a nice day.
